language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

env:
    - PEP8_IGNORE=""

# command to install dependencies
install:
    - pip install pep8

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pep8 --ignore=$PEP8_IGNORE -r --show-source . ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then python -c 'import conttest' ; fi

notifications:
  email: false
